### ISSUE TITLE
Whether secvideo_demo will work on new OP-TEE?

### ISSUE THREAD

**Issue by ajithpv** [jforissier/secvideo_demo#3]
Hi,
I would like to do a LCD image dump in OP-TEE and the only reference which I have seen so far is secvideo_demo (I know it is a prototype).
I'm using latest OP-TEE and would like to know whether this demo code can be taken for the reference. If anything changed/modified/removed, then please let me know that also.
PS: The path and folder structure is looking different from  old OP-TEE to new OP-TEE hence asking this query.

**Comment by ajithpv** [comment]
@jforissier could you please reply to the above query?

**Comment by vchong** [comment]
@jforissier is on summer holiday.
This demo is based on very old snapshots of the OP-TEE repos. There's currently no plan to update this. If you're able to port this to the latest repos, that would be great. Otherwise refer to http://connect.linaro.org/resource/bkk16/bkk16-201 for recent work in this area. If you don't a PlayReady license then the clearkey implementation is an alternative.

**Comment by ajithpv** [comment]
Thank you very much for the reply @vchong .

**Comment by ajithpv** [comment]
I would like to know how I can take the image via shared memory and dumped on the image on LCD through secured memory. The secvideo_demo is doing memory copy to FRAMEBUFFER_ADDRESS (i.e. 0xff000000) but, I didn't get how to make this destination address secured to OP-TEE and which in-turn dump on LCD.
Any help would be appriciated.

**Comment by ajithpv** [comment]
@vchong or @jforissier , could you please give some idea on the above query?
